### ISSUE TITLE
Enforce using Python Black - Python code formatter

### ISSUE THREAD

**Issue by garoller** [wtg/petitions-rewrite#19]
[Python Black Docs](https://black.readthedocs.io/en/stable/)

Start using this a standard. Include documentation for installation/setup in Wiki.
Set up checks on the repository to check for the correct format.

**Comment by kochman** [comment]
I'm a big fan of this. We did it on [Pipeline](https://github.com/thepoly/pipeline) with Travis. See [the .travis.yml](https://github.com/thepoly/pipeline/blob/ad221b1eab7827cfd80e2504e6988435f9134287/.travis.yml#L28) for the command it executes.

The only thing that needs to happen before is that Black gets installed—could be with pip and a requirements.txt or whatever. Pipeline uses [pipenv](https://pipenv.readthedocs.io/en/latest/).
