### ISSUE TITLE
Make required fields in petition model

### ISSUE THREAD

**Issue by lqlin33** [wtg/petitions-rewrite#28]
Currently a petition can be made without entering any info about it, but certain fields like a title should be required when creating a petition. Would involve changes to the petitions model.

**Comment by sjhuang26** [comment]
I'll do this issue.

**Comment by sjhuang26** [comment]
The petition title and description is already required. Fields in Django are required by default.

![image](https://user-images.githubusercontent.com/29558846/55297783-81219500-53f7-11e9-8349-1c67f0394f4b.png)

Closing issue.
